require ${COREBASE}/../meta-freescale-3rdparty/conf/machine/imx6qsabrelite.conf

BBMASK += "meta-boundary/recipes-kernel/linux/linux-boundary_%.bbappend"

DISTRO_FEATURES_remove = "sysvinit"

# Use systemd init manager.
DISTRO_FEATURES_append = " systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_dev_manager = "udev"
VIRTUAL-RUNTIME_init_manager = "systemd"

# Change Image features for systemd.
IMAGE_DEV_MANAGER = "udev"
IMAGE_INIT_MANAGER = "systemd"
IMAGE_INITSCRIPTS = ""

MACHINE_FEATURES += "external-ap"
