require ${WORKSPACE}/sources/meta-freescale-3rdparty/conf/machine/imx6qsabrelite.conf
require conf/machine/include/external-ap.inc

BBMASK += "meta-boundary/recipes-kernel/linux/linux-boundary_%.bbappend"

TARGET = "eap-imx"
