require ${WORKSPACE}/sources/meta-freescale/conf/machine/imx6sxsabresd.conf
require conf/machine/include/external-ap.inc

IMX_DEFAULT_KERNEL_mx6 = "linux-imx"

TARGET = "eap-imx"

BBMASK .= "|meta-qti-eap/recipes-kernel/linux/linux-imx_4.9.88.bbappend"
BBMASK .= "|meta-qti-eap/recipes-kernel/linux/linux-imx_4.14.62.bbappend"
