require ${COREBASE}/meta/conf/machine/qemuarm64.conf
require conf/machine/include/external-ap.inc

PREFERRED_VERSION_linux-yocto = "4.9.%"

TARGET = "eap-imx64"

BBMASK += "meta-qti-eap/recipes-kernel/linux/linux-imx_4.9.88.bbappend"
BBMASK += "meta-qti-eap/recipes-kernel/linux/linux-imx_4.14.62.bbappend"
