#!/bin/sh
#
# Copyright (c) 2020, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# DESCRIPTION: Add MDM ADB to EAP USB bridge.

MDM_COMP=$(lsusb | grep 05c6 | cut -d':' -f3 | cut -d' ' -f1)
if [ -z "$MDM_COMP" ]; then
    echo "MDM not found. Exiting..."
    exit 1
fi

case $MDM_COMP in
    9102)
        ADB_INTERFACE=8
        ;;
    9104)
        ADB_INTERFACE=3
        ;;
    9106)
        ADB_INTERFACE=7
        ;;
    910A)
        ADB_INTERFACE=7
        ;;
    910C)
        ADB_INTERFACE=6
        ;;
    *)
        echo "MDM Composition not supported"
        exit 1
        ;;
esac

# Change composition to 9008 (disables EAP ADB)
usb_composition 9008 n n y n
sleep 2
echo "" > /sys/kernel/config/usb_gadget/g1/UDC
sleep 2
usb_bridge_config -e $ADB_INTERFACE
