#!/bin/sh
#
# Copyright (c) 2018, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# DESCRIPTION: Setup USB pass through for selected interfaces from host
# port to device port. E.g. To export interface 0 and 1 of the USB device
# to the USB host use: "usb_bridge_config 0 1"

SCRIPT_NAME=$0
VID=0x05C6
PID=0x9FFF
UDC_NAME=ci_hdrc.0
GADGET_DIR=/sys/kernel/config/usb_gadget
STRINGS_DIR=strings/0x409

print_usage () {
    echo "Usage: $SCRIPT_NAME <iface number> ... <iface number>"
}

if [ "$#" -le 0 ]; then
    print_usage
    exit 1
fi

# Setup gadget device
cd $GADGET_DIR
if [ ! -d "$GADGET_DIR/g1" ]; then
    mkdir g1
else
    # Check if gadget already enabled
    IS_ENABLE=$(cat $GADGET_DIR/g1/UDC)
    if [ "$IS_ENABLE" == "$UDC_NAME" ]; then
        echo "Gadget is enabled. Disable gadget before calling $SCRIPT_NAME"
        echo "echo \"\" > $GADGET_DIR/g1/UDC"
        exit 1
    fi
fi

cd g1

if [ ! -d "$GADGET_DIR/g1/$STRINGS_DIR" ]; then
    mkdir $STRINGS_DIR
fi

echo "QTI" > $STRINGS_DIR/manufacturer
echo "QTI Modem" > $STRINGS_DIR/product
echo "123456" > $STRINGS_DIR/serialnumber
echo $VID > idVendor
echo $PID > idProduct

if [ ! -d "$GADGET_DIR/g1/configs/ub.1" ]; then
    mkdir configs/ub.1
fi

for intf in "$@"; do
    if [ ! -d "$GADGET_DIR/g1/functions/usb_bridge.$intf" ]; then
        mkdir functions/usb_bridge.$intf
    fi
    if [ ! -L "$GADGET_DIR/g1/configs/ub.1/usb_bridge.$intf" ]; then
        ln -s functions/usb_bridge.$intf configs/ub.1
    fi
done

echo "$UDC_NAME" > UDC
