# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "qti-eap"
BBFILE_PATTERN_qti-eap = "^${LAYERDIR}/"
BBFILE_PRIORITY_qti-eap = "6"

LAYERSERIES_COMPAT_qti-eap = "krogoth"
LAYERSERIES_COMPAT_qti-eap += "morty"
LAYERSERIES_COMPAT_qti-eap += "pyro"
LAYERSERIES_COMPAT_qti-eap += "rocko"
LAYERSERIES_COMPAT_qti-eap += "sumo"

LAYERDEPENDS_qti-eap = "core"
LAYERDEPENDS_qti-eap += "openembedded-layer"
LAYERDEPENDS_qti-eap += "networking-layer"
LAYERDEPENDS_qti-eap += "meta-python"

BB_DANGLINGAPPENDS_WARNONLY ??= "1"

WITH_PROP_LAYER ?= "no"
