# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "qti-eap"
BBFILE_PATTERN_qti-eap = "^${LAYERDIR}/"
BBFILE_PRIORITY_qti-eap = "6"

LAYERSERIES_COMPAT_qti-eap = "sumo"
LAYERSERIES_COMPAT_qti-eap += "thud"

LAYERDEPENDS_qti-eap = "core"

BB_DANGLINGAPPENDS_WARNONLY ??= "1"

WITH_PROP_LAYER ?= "no"
LAYERSERIES_COMPAT_qti-eap += "zeus"
